// API URL
export const PRODUCTS_API = 'https://api.escuelajs.co/api/v1/products';

// ACTIONS
export const GET_PRODUCTS = "GET_PRODUCTS";
export const ADDITEMTOCART = "ADDITEMTOCART";
export const DELETEITEMFROMCART = "DELETEITEMFROMCART";
export const DELETEQUANTITYITEMFROMCART = "DELETEQUANTITYITEMFROMCART";
export const SET_PRODUCTS = "SET_PRODUCTS";
export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT";
export const SET_SINGLE_PRODUCT = "SET_SINGLE_PRODUCT";
